---

- name: install tftpd
  yum:
    pkg: tftp-server

- name: install file name mappings
  template:
    src: mapping.conf.j2
    dest: '{{ tftpd_mapfile }}'
    owner: root
    group: root
    mode: 0644
  when: tftpd_mappings is defined
  tags:
    - tftpd-mapping

- name: install xinetd script
  template:
    src: xinetd-tftp.j2
    dest: /etc/xinetd.d/tftp
    owner: root
    group: root
    mode: 0644
  register: __tftpd_configuration
  tags:
    - tftpd-config

- name: reload xinetd # noqa 503
  service:
    name: xinetd
    state: reloaded
  when: __tftpd_configuration.changed
  tags:
    - tftpd-config

...
